[project]
src = "src"
out = "out"
dot_env = ".env"
save_abi_path = "abis"
explorer_api_key = "$EXPLORER_API_KEY"
default_network_name = "eth-forked"

[networks.eth-forked]
fork = true
url = "$MAINNET_RPC_URL"
default_account_name = "anvil1"

[networks.contracts]
usdc = { abi = "abis/usdc.json", external = true }
wbtc = { abi = "abis/wbtc.json", external = true }
uniswap_swap_router = { abi = "abis/uniswap_swap_router.json", external = true }

[networks.eth-forked.contracts]
usdc = { address = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48" }
wbtc = { address = "0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599" }
uniswap_swap_router = { address = "0xE592427A0AEce92De3Edee1F18E0157C05861564" }

[networks.pyevm]
is_zksync = false

[networks.anvil]
url = "http://127.0.0.1:8545"
prompt_live = false
save_to_db = false
chain_id = 31337

[networks.sepolia]
url = "$ "
chain_id = 11155111

[networks.zksync-sepolia]
url = "https://sepolia.era.zksync.dev"
chain_id = 300
is_zksync = true
prompt_live = true
